name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Linux install openssh-server
        run: sudo apt install -y openssh-server
      - name: Linux install openssh-client
        run: sudo apt install -y openssh-client
      - name: Linux install GitHub 
        run: sudo apt install -y git
      - name: Syntax check
        run: python -m compileall -q .
      - name: Run tests
        run: python -m pytest -q
